.PHONY: clean

bin/hw2: test/ut_main.cpp test/ut_sort.cpp test/ut_shape.cpp src/shape.h src/circle.h src/triangle.h src/rectangle.h
	g++ -std=c++11 test/ut_main.cpp -o bin/hw2 -lgtest -lpthread

clean:	
